import { SidebarTrigger, SidebarProvider } from '@/components/ui/sidebar'
import { Gabarito } from 'next/font/google'
import { ThemeProvider } from '../components/ThemeProvider/themeprovider'
import { ReduxProvider } from '@/redux/reduxprovider'
import { Toaster } from 'sonner'
import { Metadata } from 'next'
import GlobalComps from '@/components/GlobalComps/globalcomps'
import './globals.css'

export const metadata: Metadata = {
  title: 'Intentify',
  icons: {
    icon: [
      { url: '/favicon-96x96.png', type: 'image/png', sizes: '96x96' },
      { url: '/favicon.svg', type: 'image/svg+xml' },
    ],
    shortcut: '/favicon.ico',
    apple: '/apple-touch-icon.png',
  },
  manifest: '/site.webmanifest',
  description: 'Generated by create next app',
}

const gabarito = Gabarito({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={gabarito.className}>
      <ThemeProvider
        attribute="class"
        defaultTheme="light"
        enableSystem
        disableTransitionOnChange
        >
      <SidebarProvider>
      <ReduxProvider>
        <GlobalComps/>
        <SidebarTrigger/>
        <Toaster richColors position="bottom-center"/>
        {children}
      </ReduxProvider>
      </SidebarProvider>
      </ThemeProvider>
      </body>
    </html>
  )
}
