import { SidebarTrigger, SidebarProvider } from '@/src/components/ui/sidebar'
import { AppSidebar } from '@/src/components/AppSidebar/appsidebar'
import './globals.css'
import { Gabarito } from 'next/font/google'
import { ThemeProvider } from '../components/ThemeProvider/themeprovider'
import { ModeToggle } from '../components/ModeToggle/modetoggle'

export const metadata = {
  title: 'Intentify',
  description: 'Generated by create next app',
}

const gabarito = Gabarito({
  weight: '400',
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={gabarito.className}>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        >
      <SidebarProvider>
        <AppSidebar/>
        <ModeToggle/>
        <SidebarTrigger/>
        {children}
      </SidebarProvider>
      </ThemeProvider>
      </body>
    </html>
  )
}
